---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronotrains
  namespace: chronotrains
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  selector:
    matchLabels:
      app: chronotrains
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: chronotrains
    spec:
      containers:
        - name: chronotrains
          image: gcr.io/PROJECT_ID/IMAGE_NAME:TAG
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: chronotrains-envs
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chronotrains
  name: chronotrains
  namespace: chronotrains
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    app: chronotrains
